name: Tests

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        name: PHP ${{ matrix.php }} Redis ${{ matrix.redis }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '8.0'
                    - '8.1'
                    - '8.2'
                redis:
                    - 5
                    - 6
                    - 7
        services:
            redis:
                image: redis:${{ matrix.redis }}
                options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
                ports:
                    - 6379:6379
        steps:

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Setup PHP with Composer and extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: ${{ (matrix.php == '8.1' && matrix.redis == '7') && 'xdebug' || 'none' }}

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    dependency-versions: highest

            -   name: Run PHPUnit Feature tests
                if: ${{ matrix.php != '8.1' || matrix.redis != '7' }}
                run: vendor/bin/phpunit --verbose --log-junit report.xml

            -   name: Run PHPUnit tests with coverage
                if: ${{ matrix.php == '8.1' && matrix.redis == '7' }}
                run: vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --coverage-filter ./src --log-junit report.xml

            -   name: Test Report
                uses: dorny/test-reporter@v1
                continue-on-error: true
                if: success() || failure()
                with:
                    path: "report.xml"
                    name: Test Report PHP ${{ matrix.php }} Redis ${{ matrix.redis }}
                    reporter: java-junit
                    list-suites: all
                    list-tests: all
                    max-annotations: 10
                    fail-on-error: 'false'
